version: '1.0'
services:
  webservice:
    container_name: "PHP-SERVER"
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 81:80
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: quizzDB 
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3206:3306"